/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/** WithRequired type helpers */
type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export interface paths {
  "/events": {
    /** List all events */
    get: operations["getEvents"];
  };
  "/events/{eventId}": {
    /** Info for a specific event */
    get: operations["getEventById"];
  };
  "/events/{eventId}/age-groups": {
    /** List all age groups of an event */
    get: operations["getAgeGroups"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}": {
    /** Info for a specific age group */
    get: operations["getAgeGroupById"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/athletes": {
    /** List all athletes of an age group of an event */
    get: operations["getAthletesByAgeGroup"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/competitions": {
    /** List all competitions of an age group */
    get: operations["getCompetitions"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/competitions/{competitionId}": {
    /** Info for a specific competition */
    get: operations["getCompetitionById"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/competitions/{competitionId}/rounds": {
    /** List all rounds of a competition */
    get: operations["getRounds"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/competitions/{competitionId}/rounds/{roundId}": {
    /** Info for a specific round */
    get: operations["getRoundById"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/competitions/{competitionId}/rounds/{roundId}/races": {
    /** List all races of a round */
    get: operations["getRaces"];
  };
  "/events/{eventId}/age-groups/{ageGroupId}/competitions/{competitionId}/rounds/{roundId}/races/{raceId}": {
    /** Info for a specific race */
    get: operations["getRaceById"];
  };
  "/events/{eventId}/athletes": {
    /** List all athletes of an event */
    get: operations["getAthletes"];
  };
  "/events/{eventId}/athletes/{athleteId}": {
    /** Info for a specific athlete */
    get: operations["getAgeGroupById"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Event: {
      id: string;
      slug: string;
      public: boolean;
      name: string;
      /** Format: date */
      dateBegin: string;
      /** Format: date */
      dateEnd: string;
    };
    Events: {
      items: components["schemas"]["Event"][];
      total: number;
    };
    AgeGroup: {
      id: string;
      name: string;
      /** @enum {string|null} */
      gender: "male" | "female" | null;
      competitions: components["schemas"]["Competition"][];
      event: string;
    };
    AgeGroups: {
      items: components["schemas"]["AgeGroup"][];
      total: number;
    };
    Athlete: {
      id: string;
      bib?: number;
      /** @description Omitted, if athlete didn't sign the privacy policy */
      lastName?: string;
      /** @description Omitted, if athlete didn't sign the privacy policy */
      firstName?: string;
      club?: string;
      team?: string;
      nation?: string;
      overallResult: {
        rank?: number;
      };
      competitionResults: {
        competition: string;
        rank?: number;
      }[];
      event: string;
      ageGroup?: string;
    };
    Athletes: {
      items: components["schemas"]["Athlete"][];
      total: number;
    };
    Competition: {
      id: string;
      name: string;
      rounds: components["schemas"]["Round"][];
      ageGroup: string;
      event: string;
    };
    Competitions: {
      items: components["schemas"]["Competition"][];
      total: number;
    };
    Round: {
      id: string;
      name: string;
      seeded: boolean;
      races: components["schemas"]["Race"][];
    };
    Rounds: {
      items: components["schemas"]["Round"][];
      total: number;
    };
    Race: {
      id: string;
      done: boolean;
      seeded: boolean;
    };
    Races: {
      items: components["schemas"]["Race"][];
      total: number;
    };
    FullRace: WithRequired<
      {
        athletes: components["schemas"]["RaceAthlete"][];
      } & components["schemas"]["Race"],
      "athletes"
    >;
    RaceAthlete: {
      /** @description Start position of the athlete */
      startPos?: number;
      /** @description Final rank of the athlete */
      rank?: number;
      athlete: components["schemas"]["Athlete"];
    };
    Error: {
      statusCode: number;
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** List all events */
  getEvents: {
    responses: {
      /** @description An array of events */
      200: {
        content: {
          "application/json": components["schemas"]["Events"];
        };
      };
    };
  };
  /** Info for a specific event */
  getEventById: {
    parameters: {
      path: {
        /** @description ID of the event to be fetched */
        eventId: string;
      };
    };
    responses: {
      /** @description Event object */
      200: {
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all age groups of an event */
  getAgeGroups: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
      };
    };
    responses: {
      /** @description An array of age groups */
      200: {
        content: {
          "application/json": components["schemas"]["AgeGroups"];
        };
      };
      /** @description Event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Info for a specific athlete */
  getAgeGroupById: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the athlete to be fetched */
        athleteId: string;
      };
    };
    responses: {
      /** @description athlete object */
      200: {
        content: {
          "application/json": components["schemas"]["Athlete"];
        };
      };
      /** @description Athlete not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all athletes of an age group of an event */
  getAthletesByAgeGroup: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
      };
    };
    responses: {
      /** @description An array of athletes */
      200: {
        content: {
          "application/json": components["schemas"]["Athletes"];
        };
      };
      /** @description Event or age group not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all competitions of an age group */
  getCompetitions: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
      };
    };
    responses: {
      /** @description An array of competitions */
      200: {
        content: {
          "application/json": components["schemas"]["Competitions"];
        };
      };
      /** @description Age group or event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Info for a specific competition */
  getCompetitionById: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
        /** @description ID of the competition */
        competitionId: string;
      };
    };
    responses: {
      /** @description Competition object */
      200: {
        content: {
          "application/json": components["schemas"]["Competition"];
        };
      };
      /** @description Competition, age group, or event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all rounds of a competition */
  getRounds: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
        /** @description ID of the competition */
        competitionId: string;
      };
    };
    responses: {
      /** @description An array of rounds */
      200: {
        content: {
          "application/json": components["schemas"]["Round"];
        };
      };
      /** @description Competition, age group or event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Info for a specific round */
  getRoundById: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
        /** @description ID of the competition */
        competitionId: string;
        /** @description ID of the round */
        roundId: string;
      };
    };
    responses: {
      /** @description Round object */
      200: {
        content: {
          "application/json": components["schemas"]["Round"];
        };
      };
      /** @description Round, competition, age group, or event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all races of a round */
  getRaces: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
        /** @description ID of the competition */
        competitionId: string;
        /** @description ID of the round */
        roundId: string;
      };
    };
    responses: {
      /** @description An array of races */
      200: {
        content: {
          "application/json": components["schemas"]["Races"];
        };
      };
      /** @description Round. competition, age group or event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Info for a specific race */
  getRaceById: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
        /** @description ID of the age group */
        ageGroupId: string;
        /** @description ID of the competition */
        competitionId: string;
        /** @description ID of the round */
        roundId: string;
        /** @description ID of the race */
        raceId: string;
      };
    };
    responses: {
      /** @description Race object */
      200: {
        content: {
          "application/json": components["schemas"]["Race"];
        };
      };
      /** @description Race, round, competition, age group, or event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all athletes of an event */
  getAthletes: {
    parameters: {
      path: {
        /** @description ID of the event */
        eventId: string;
      };
    };
    responses: {
      /** @description An array of athletes */
      200: {
        content: {
          "application/json": components["schemas"]["Athletes"];
        };
      };
      /** @description Event not found */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
